server:
  context-path: /
  port: 8081

oauth:
  resourceId: resource-server-demo
  signingKey: MaYzkSjmkzPC57L

logging:
  # -- log to file --
  # if you use 'logging.path', then the log file is created relative to that path
  # path: some/path
  file: logs/springboot-authn-server-demo.log
  pattern:
    #console: "%d %-5level %logger : %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(18971){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.standard.demo: DEBUG